platform :ios, '10.0'

target 'CoolestProjects' do
  use_frameworks!

  # Pods for CoolestProjects
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  
  pod 'JSONModel'
  pod 'SDWebImage', '~> 3.7.6'
  
  pod 'Alamofire', '~> 4.3'
  pod 'Gloss', '~> 1.2'    

  pod 'EstimoteSDK', '~> 4.13'

  target 'CoolestProjectsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do | installer |
    require 'fileutils'
    FileUtils.cp_r('Pods/Target Support Files/Pods-CoolestProjects/Pods-CoolestProjects-acknowledgements.plist', 'CoolestProjects/Resources/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
end
