platform :ios, '9.0'

target 'CoolestProjects' do
  use_frameworks!

  # Pods for CoolestProjects
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  
  pod 'JSONModel'
  pod 'SWRevealViewController' 
  pod 'SDWebImage', '~> 3.7.6'
  
  pod 'Alamofire', '~> 3.4.0'
  pod 'Gloss', '~> 0.7'    

  target 'CoolestProjectsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do | installer |
    require 'fileutils'
    FileUtils.cp_r('Pods/Target Support Files/Pods-CoolestProjects/Pods-CoolestProjects-acknowledgements.plist', 'CoolestProjects/Resources/Settings.bundle/Acknowledgements.plist', :remove_destination => true)
end
