# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CoolestProjects' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for CoolestProjects
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

  pod 'JSONModel'

  target 'CoolestProjectsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
